[project]
dependencies    = []
description     = "Add your description here"
name            = "procon-ws"
readme          = "README.md"
requires-python = ">=3.13"
version         = "0.1.0"

[dependency-groups]
dev = ["online-judge-tools>=11.5.1", "setuptools>=80.9.0"]
